### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DataDrivenDiffEq.jl#12]
Before registering, I think we should make sure the name is settled. I do like the name DataDrivenDiffEq. It's doing a few different things, since Koopman methods are in some sense solving an estimation problem of a linear operator, while SInDy is doing system identification. StructuralEstimationDiffEq.jl sounds bad, and StructuralEstimation.jl is non-informative. So maybe DataDrivenDiffEq.jl is the best choice, the docs page on it should still be named "Structural Estimation"? Seems like it works, but I wanted to bounce this around before finalizing the process.

**Comment by AlCap23** [comment]
Let's keep it at data driven. One could make the case that operators can be interpreted as some kind of structure, but overall it's about discovery of maps and functions based on the collected data.

**Comment by ChrisRackauckas** [comment]
Sounds good to me!

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
