### ISSUE TITLE
Check the validity of SInDy regression

### ISSUE THREAD

**Issue by AlCap23** [JuliaDiffEq/DataDrivenDiffEq.jl#28]
As @gabrevaya said to me on slack, SInDy does not always converge on numerical derivatives provided by dierkx ( and possible others ).

This needs to be checked with the original examples.

**Comment by ChrisRackauckas** [comment]
yeah I noticed this in the docs I was writing. Seems peculiar.

**Comment by AlCap23** [comment]
I just tried the cubic linear model given in the [supplementary files](https://www.pnas.org/content/pnas/suppl/2016/03/23/1517384113.DCSupplemental/pnas.1517384113.sapp.pdf). 

For the derivatives spit out by the ```DESolution`` of the problem everything works fine. If I use Dierkx on the same data the algorithm breaks. Both do. This is pretty annoying, since not even noise is present.

The maximum difference between the derivatives of the *true* solution and the interpolation is approximately 0.2. 

Also, given more data points ( setting dt = 1e-3 ) results in breakdown of convex and wrong results of strridge. But this could be related to the timescales of the system and the gradient of the functions.

I also tried out [SparseRegression.jl](https://github.com/joshday/SparseRegression.jl) which provides a save estimation of the structure until certain noise levels.

I will investigate this further, but switching is at least an option. Also, this shows the importance of implementing the algorithms mentioned in #24.

**Comment by gabrevaya** [comment]
I was checking the [supplementary files](https://www.pnas.org/content/pnas/suppl/2016/03/23/1517384113.DCSupplemental/pnas.1517384113.sapp.pdf) that @AlCap23 mentioned and I noticed (Figure 20) that the threshold (our epsilon, their lambda) that we were using was too small (1e-10 vs 1e-3 to 1e0). Also, the sampling frequency that we were using was too small.

Using epsilon = 1e-2 and saveat=0.1, SINDy seems to work both with the derivatives obtained with Dierckx and with the true derivatives. (All of these working with the sequential thresholded least squares, I'll try with sparseConvex later).

However, I see that the convergence to the right basis depends too much on a good choice of epsilon. I'd like to try to implement [SR3](https://www.researchgate.net/profile/Peng_Zheng21/publication/326438491_Sparse_Relaxed_Regularized_Regression_SR3/links/5b8d4ca7a6fdcc1ddd0868d1/Sparse-Relaxed-Regularized-Regression-SR3.pdf), which was used in [one of the most recent SINDy papers](https://arxiv.org/pdf/1906.10612.pdf) and seems to be more robust to outliers, able to include additional structure and nonlinear parameter estimation.

Maybe my friends @saravkin and @zhengp0 (two of the main authors of SR3) would like to help in its Julia implementation? :)

**Comment by AlCap23** [comment]
Nice! Than I can focus on the numerical derivative and noise filtering.

**Comment by ChrisRackauckas** [comment]
We should probably use Lasso.jl: https://github.com/JuliaStats/Lasso.jl . Linear lasso regression has an analytical solution (https://en.wikipedia.org/wiki/Lasso_(statistics)) that these can use instead of a convex optimization.

**Comment by AlCap23** [comment]
After exploring the optimizers a bit, I think most of the problems are related to the quality of the data - time intervals, subsampling of high excitation of the individual terms and noise robustness. This has been also mentioned in some of the papers by Brunton ( finding good trajectories is hard ).

I think the algorithms used within #33 and #36 are sufficient and the interface, while most likely not perfect, is flexible enough to allow arbitrary implementation via other pkgs ( e.g. Lasso ) or extensions ( e.g. the ones mentioned in #27 ). 

Additionally, once more feedback , issues and hopefully PRs :) are available the hidden misses or errors will emerge.

**Comment by AlCap23** [comment]
I'll close this for now.
