### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DataDrivenDiffEq.jl#32]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator  register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

@JuliaRegistrator register subdir=lib/DataDrivenDMD
@JuliaRegistrator register subdir=lib/DataDrivenSparse
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

@JuliaRegistrator register subdir=lib/DataDrivenDMD
@JuliaRegistrator register subdir=lib/DataDrivenSparse
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenDMD

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSparse

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenDMD

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSparse

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSparse

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

@JuliaRegistrator register subdir=lib/DataDrivenDMD
@JuliaRegistrator register subdir=lib/DataDrivenSparse
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSparse

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSR

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenSparse

**Comment by AlCap23** [comment]
@JuliaRegistrator register()

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenLux

**Comment by AlCap23** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenLux

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenLux

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register subdir=lib/DataDrivenLux

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/DataDrivenLux

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/DataDrivenLux

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/DataDrivenDMD

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/DataDrivenSR

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/DataDrivenSparse

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register() subdir=lib/DataDrivenLux

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
