### ISSUE TITLE
Time(t) as a basis?

### ISSUE THREAD

**Issue by Reichenbach95** [JuliaDiffEq/DataDrivenDiffEq.jl#58]
Is it possible to have just time(t) as a basis along with u1(t), u2(t) etc..?

**Comment by AlCap23** [comment]
In theory, you can handle `t` just as you would handle `u1 u2 u3`etc. So append it to the variables passed in like

```julia
b = Basis(eqs, [u...; t])
```
And append a row to the data matrix.

However, this is not handled well in the current `dynamics(b)` / `ODESystem(b)`. But I will get onto that in the next few days.

**Comment by Reichenbach95** [comment]
Cool..Thanks!

**Comment by AlCap23** [comment]
Todo : Add this to the examples.

**Comment by AlCap23** [comment]
Closed via #60
